#!/usr/bin/env php
<?php
require_once __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

// dic
$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__));
$loader->load(__DIR__.'/resources/config/services.yml');

// app
$application = new Application();
$application->run();




